version: "3.9"
services:
  local_posgresql:
    container_name: digital_postgres
    image: postgres:12.8
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: local
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
  local_task:
    container_name: digital_signature_2021
    image: "digital_signature_2021:latest"
    command: ./main