version: "3.2"
services:
  postgres:
    container_name: postgres_thesis
    image: postgres:11.4
    environment:
      POSTGRES_DB: digital_signatural
      POSTGRES_USER: root
      POSTGRES_PASSWORD: local
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5435:5432"
volumes:
  postgres-data: