version: "3.2"
services:
  postgres:
    container_name: postgres11
    image: postgres:11.4
    environment:
      POSTGRES_DB: digital_signatural
      POSTGRES_USER: root
      POSTGRES_PASSWORD: local
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5435:5432"
  pgadmin4: 
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: digital@gmail.com
        PGADMIN_DEFAULT_PASSWORD: local
        PGADMIN_LISTEN_PORT: 80
    ports: 
        - "8080:80"
    volumes:
        - pgadmin-data:/var/lib/pgadmin/data
    links:
        - "postgres:pgsql-server"
volumes:
  postgres-data:
  pgadmin-data: