server:
  mode: "development"
  host: "localhost"
  port: "8081"
ethereum:
  #you need to change cuongtop to your username in these bellow path 
  wallets: "/home/cuongtop/ethereum-development/wallets"
  endpoint: "/home/cuongtop/.ethereum/geth.ipc" #for mainnet "https://mainnet.infura.io"
  