server:
  mode: "development"
  host: "localhost"
  port: "8081"
ethereum:
  endpoint: "http://27.72.105.169:10199"
  keystore_path: "./wallets/keystore/"
  chain_id: 451998
  pass_admin: "123456"
database:
  host: "localhost" 
  user: "root"
  password: "local"
  database: "digital_signatural"
  port: "5433"
  env: "development"
contract: "0x34cB857974f136169f94054914B84fCAf6dd7e37"