server:
  mode: "development"
  host: "localhost"
  port: "8081"
ethereum:
  endpoint: "http://27.72.105.169:10198"
  keystore_path: "./wallets/keystore/"
  chain_id: 451998
  pass_admin: "123456"
database:
  host: "localhost" 
  port: "5435"
  user: "root"
  password: "local"
  database: "digital_signatural"
address: 
  document: "0xcc45e9AABf28b8439D29F4e5a7e6649e59A22520"
  accounts: []