server:
  mode: "development"
  host: "0.0.0.0"
  port: "10115"
ethereum:
  endpoint: "http://27.72.105.169:10198"
  keystore_path: "./wallets/keystore/"
  chain_id: 451998
  pass_admin: "123456"
database:
  host: "localhost" 
  port: "5435"
  user: "root"
  password: "local"
  database: "digital_signatural"
address: 
  document: "0xe2047de5F69f8F8142457345972355d98Ecb84B7"
  accounts: []