server:
  mode: "development"
  host: "localhost"
  port: "8081"
ethereum:
  endpoint: "http://27.72.105.169:10198"
  keystore_path: "./wallets/keystore/"
  chain_id: 451998
  pass_admin: "123456"
database:
  host: "localhost" 
  port: "5433"
  user: "root"
  password: "local"
  database: "digital_signatural"
address: 
  document: "0x5Eed6E09c13aeeBB31485d435bFAD939051F2731"
  accounts: []